#!/bin/bash

if [ "`whoami`" != "root" ]; then
	sudo "$0"
	exit
fi

if [ ! -f /usr/lib/nagios/plugins/check_procs ]; then
	echo "/usr/lib/nagios/plugins/check_procs not found, unable to check for running updates"
	exit 2
fi

ERROR=0
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt-get &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C aptitude &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C dpkg &> /dev/null || ERROR=1

if [ "$ERROR" -ne "0" ]; then
	echo "Some update/installation is currently running"
	exit 1
fi

apt update || exit 3
apt full-upgrade || exit 3
apt autoremove || exit 3
apt autoclean || exit 3
apt purge $(dpkg -l | grep '^rc' | awk '{print $2}') || exit 3

