#!/bin/bash

PACKAGES="containerd.io docker-ce"

hold() {
	echo "$1 $2" | dpkg --set-selections
}

if [ ! -f /usr/lib/nagios/plugins/check_procs ]; then
	echo "/usr/lib/nagios/plugins/check_procs not found, unable to check for running updates"
	exit 2
fi

ERROR=0
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt-get &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C aptitude &> /dev/null || ERROR=1
/usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C dpkg &> /dev/null || ERROR=1

if [ "$ERROR" -ne "0" ]; then
	echo "Not updating, some update/installation is currently running"
	exit 1
fi

UPDATES=""

for pkg in $PACKAGES; do
	INSTALLED=`apt-cache policy "$pkg" | grep 'Installed' | sed -e 's/.*: //'`
	CANDIDATE=`apt-cache policy "$pkg" | grep 'Candidate' | sed -e 's/.*: //'`

	if [ "$INSTALLED" != "$CANDIDATE" ]; then
		echo "Package $pkg needs to be updated from $INSTALLED to $CANDIDATE"
		UPDATES="$UPDATES $pkg"
	fi
done

if [ "$UPDATES" == "" ]; then
	echo "No update available"
	exit
fi

for pkg in $PACKAGES; do hold $pkg install; done

apt update

apt install -y --reinstall $UPDATES

for pkg in $PACKAGES; do hold $pkg hold; done

