#!/bin/bash

if [ "$1" == "autoconf" ]; then
	echo "yes"
	exit
fi
if [ "$1" == "config" ]; then
	echo "graph_title Size of inbox"
	echo "graph_args -l 0"
	echo "graph_vlabel Messages"
	echo "graph_category other"
	echo "size.label Messages"
	echo "graph_info Current number of messages in inbox"
	echo "size.info Current number of messages in inbox"
	exit
fi

MAILBOX_SIZE=`cat /etc/munin/mailbox_size`
echo "size.value $MAILBOX_SIZE"

