services:
  nextcloud:
    build:
      context: nextcloud-custom
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION}
    image: nextcloud-custom:${NEXTCLOUD_VERSION}
    container_name: nextcloud-cloud
    restart: always
    volumes:
      - /var/www/cloud:/var/www/html
      - /mnt/cloud:/data
      - /var/run/mysqld:/var/run/mysqld
    networks:
      - nextcloud
    depends_on:
      - redis
    ports:
      - 127.0.0.1:9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
    healthcheck:
      test: sudo -u www-data php occ status -e || exit 1
      interval: 5m
      timeout: 10s 
  cron:
    image: nextcloud-custom:${NEXTCLOUD_VERSION}
    pull_policy: never
    container_name: nextcloud-cron
    restart: unless-stopped
    init: true
    volumes:
      - /var/www/cloud:/var/www/html
      - /mnt/cloud:/data
      - /var/run/mysqld:/var/run/mysqld
    networks:
      - nextcloud
    entrypoint: [ "/cron.sh" ]
    depends_on:
      - nextcloud
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
    healthcheck:
      test: sudo -u www-data php occ status -e || exit 1
      interval: 5m
      timeout: 10s 
  redis:
    image: redis:${REDIS_VERSION}
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud
    healthcheck:
      test: redis-cli --raw incr ping || exit 1
      interval: 5m
      timeout: 10s
      start_interval: 10s
      start_period: 10s

networks:
  nextcloud:
    external: True


